/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:20 )
 * Generated by 
*/
package com.gotracrat.managelocation.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for AspnetApplications entity stored in table aspnet_Applications.
 * This class is a "record entity" without JPA links.
 * @author Prabhakar
 */
@Entity
@Table(name="aspnet_Applications", schema="dbo" )
public class AspnetApplications implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ApplicationId", nullable=false, length=36)
    private String applicationid ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="ApplicationName", nullable=false)
    private String applicationname ;     @Column(name="LoweredApplicationName", nullable=false)
    private String loweredapplicationname ;     @Column(name="Description")
    private String description ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AspnetApplications() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setApplicationid(String applicationid) {
        this.applicationid = applicationid ;
    }
	public String getApplicationid() {
        return this.applicationid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : ApplicationName (nvarchar) 
	public void setApplicationname(String applicationname) {this.applicationname = applicationname;}
	public String getApplicationname() {return this.applicationname;}

	//--- DATABASE MAPPING : LoweredApplicationName (nvarchar) 
	public void setLoweredapplicationname(String loweredapplicationname) {this.loweredapplicationname = loweredapplicationname;}
	public String getLoweredapplicationname() {return this.loweredapplicationname;}

	//--- DATABASE MAPPING : Description (nvarchar) 
	public void setDescription(String description) {this.description = description;}
	public String getDescription() {return this.description;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(applicationid); 
		sb.append(applicationname); 
		sb.append("|"); 
		sb.append(loweredapplicationname); 
		sb.append("|"); 
		sb.append(description); 
        return sb.toString();
    }
}