/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:23 )
 * Generated by
 */
package com.gotracrat.managelocation.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Profile entity stored in table Profile.
 * This class is a "record entity" without JPA links.
 *
 * @author Prabhakar
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "Profile", schema = "dbo")
public class Profile implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ProfileID", nullable = false)
    private Integer profileid;
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name = "UserID", nullable = false, length = 36)
    private String userid;
    @Column(name = "FirstName", length = 50)
    private String firstname;
    @Column(name = "LastName", length = 50)
    private String lastname;
    @Column(name = "JobTitle", length = 50)
    private String jobtitle;
    @Column(name = "Department", length = 50)
    private String department;
    @Column(name = "Phone", length = 20)
    private String phone;
    @Column(name = "MobilePhone", length = 14)
    private String mobilephone;
    @Column(name = "Fax", length = 14)
    private String fax;
    @Column(name = "AcceptedTerms", nullable = false)
    private Boolean acceptedterms;
    @Column(name = "IsOwnerAdmin", nullable = false)
    private Boolean isowneradmin;
    @Column(name = "CompanyID")
    private Integer companyid;
    @Column(name = "SendReceiveRFQ", nullable = false)
    private Boolean sendreceiverfq;
    @Column(name = "TopLocationID")
    private Integer toplocationid;
    @Column(name = "PreferredLocationID")
    private Integer preferredlocationid;
    @Column(name = "HidePricing", nullable = false)
    private Boolean hidepricing;
	@Column(name = "IsOwnerAdminReadOnly")
	private Boolean isOwnerAdminReadOnly;

}
