/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:25 )
 * Generated by 
*/
package com.gotracrat.managelocation.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Composite primary key for entity "Usersecurity" ( stored in table "UserSecurity" )
 * @author Prabhakar
 */
 @Embeddable
public class UsersecurityKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="UserID", nullable=false, length=36)
    private String userid ;
    @Column(name="CompanyID", nullable=false)
    private Integer companyid ;
    @Column(name="LocationID", nullable=false)
    private Integer locationid ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public UsersecurityKey() {
        super();
    }

    public UsersecurityKey(String userid, Integer companyid, Integer locationid) {
        super();
        this.userid = userid ;
        this.companyid = companyid ;
        this.locationid = locationid ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
	public void setUserid(String value) {
        this.userid = value;
    }
	public String getUserid() {
        return this.userid;
    }

	public void setCompanyid(Integer value) {
        this.companyid = value;
    }
	public Integer getCompanyid() {
        return this.companyid;
    }

	public void setLocationid(Integer value) {
        this.locationid = value;
    }
	public Integer getLocationid() {
        return this.locationid;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(userid); 
		sb.append("|"); 
		sb.append(companyid); 
		sb.append("|"); 
		sb.append(locationid); 
        return sb.toString();
    }
}
