/*
 * Created on 2018-11-29 ( Date ISO 2018-11-29 - Time 19:27:59 )
 * Generated by Prabhakar
*/
package com.gotracrat.managelocation.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(name = "vwRepairLog", schema = "dbo")
public class VwRepairLog implements Serializable {

	@Id
	@Column(name = "RepairLogId")
	private Integer repairLogId;
	@Column(name = "ItemId", nullable = false)
	private Integer itemId;
	@Column(name = "RFQNumber", length = 50)
	private String rfqnumber;
	@Column(name = "PONumber", length = 50)
	private String ponumber;
	@Column(name = "RepairVendorNumber")
	private String repairvendornumber;
	@Column(name = "JobNumber")
	private String jobnumber;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateInitiated", nullable = false)
	private Date dateinitiated;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateAcknowledged")
	private Date dateacknowledged;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EstimatedCompletion")
	private Date estimatedcompletion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActualCompletion")
	private Date actualCompletion;
	@Column(name = "RepairCost")
	private BigDecimal repaircost;
	@Column(name = "IsWarranty")
	private Boolean iswarranty;
	@Column(name = "WarrantyType", length = 50)
	private String warrantytype;
	@Column(name = "FailureType", length = 255)
	private String failuretype;
	@Column(name = "FailureCause", length = 255)
	private String failurecause;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FailureDate")
	private Date failuredate;
	@Column(name = "RepairLocationID", nullable = false)
	private Integer repairlocationid;
	@Column(name = "RepairCompanyID")
	private Integer repaircompanyid;
	@Column(name = "TransferLogID")
	private Integer transferLogId;
	@Column(name = "RepairNotes")
	private String repairNotes;
	@Column(name = "Tag")
	private String tag;
	@Column(name = "ItemTypeID")
	private Integer itemTypeId;
	@Column(name = "ItemType")
	private String itemType;
	@Column(name = "RepairJobStatus")
	private String repairJobStatus;
	@Column(name = "Title", length = 255)
	private String title;
	@Column(name = "Complete")
	private Boolean complete;
	@Column(name = "CompletedBy")
	private String completedby;
	@Column (name = "Is_Active")
	private Boolean isActive;
	@Column(name = "CompanyID")
	private Integer companyId;
	@Column(name = "LocationID")
	private Integer locationId;
	@Column(name = "WarrantyExpiration")
	private String warrantyExpiration;
	@Column(name = "RepairVendorName")
	private String repairVendorName;
	@Column(name = "LocationPath")
	private String locationPath;

}