/*
 * Created on 2018-08-13 ( Date ISO 2018-08-13 - Time 16:50:45 )
 * Generated by prabhakar
*/
package com.gotracrat.managelocation.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * Persistent class for Warrantytype entity stored in table WarrantyType. This
 * class is a "record entity" without JPA links.
 * 
 * @author prabhakar
 */
@Getter
@Setter
@AllArgsConstructor
@Entity
@Table(name = "WarrantyType", schema = "dbo")
public class WarrantyType implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "WarrantyTypeID", nullable = false)
	private Integer warrantytypeid;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CompanyID", nullable = false)
	@JsonBackReference
	private Company company;
	@Column(name = "WarrantyType", nullable = false, length = 50)
	private String warrantytype;

	public WarrantyType() {
		super();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(warrantytypeid);
		sb.append("|");
		sb.append(warrantytype);
		return sb.toString();
	}
}