/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:22 )
 * Generated by 
*/
package com.gotracrat.managecompany.resource;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * 
 * 
 * @author Parasuram
 */

public class AspnetMembershipResource implements Serializable {

	private static final long serialVersionUID = 1L;

	private String userid;
	private String username;
	private String applicationid;
	private String password;
	private Integer passwordformat;
	private String passwordsalt;
	private String mobilepin;
	private String email;
	private String loweredemail;
	private String passwordquestion;
	private String passwordanswer;
	private Boolean isapproved;
	private Boolean islockedout;
	private Date createdate;
	private Date lastlogindate;
	private Date lastpasswordchangeddate;
	private Date lastlockoutdate;
	private Integer failedpasswordattemptcount;
	private Date failedpasswordattemptwindowstart;
	private Integer failedpasswordanswerattemptcount;
	private Date failedpasswordanswerattemptwindowstart;
	private String comment;
	private String resetToken;

	public AspnetMembershipResource() {
		super();
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUserid() {
		return this.userid;
	}

	// --- DATABASE MAPPING : ApplicationId (uniqueidentifier)
	public void setApplicationid(String applicationid) {
		this.applicationid = applicationid;
	}

	public String getApplicationid() {
		return this.applicationid;
	}

	public String getResetToken() {
		return resetToken;
	}

	public void setResetToken(String resetToken) {
		this.resetToken = resetToken;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPassword() {
		return this.password;
	}

	// --- DATABASE MAPPING : PasswordFormat (int)
	public void setPasswordformat(Integer passwordformat) {
		this.passwordformat = passwordformat;
	}

	public Integer getPasswordformat() {
		return this.passwordformat;
	}

	// --- DATABASE MAPPING : PasswordSalt (nvarchar)
	public void setPasswordsalt(String passwordsalt) {
		this.passwordsalt = passwordsalt;
	}

	public String getPasswordsalt() {
		return this.passwordsalt;
	}

	// --- DATABASE MAPPING : MobilePIN (nvarchar)
	public void setMobilepin(String mobilepin) {
		this.mobilepin = mobilepin;
	}

	public String getMobilepin() {
		return this.mobilepin;
	}

	// --- DATABASE MAPPING : Email (nvarchar)
	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmail() {
		return this.email;
	}

	// --- DATABASE MAPPING : LoweredEmail (nvarchar)
	public void setLoweredemail(String loweredemail) {
		this.loweredemail = loweredemail;
	}

	public String getLoweredemail() {
		return this.loweredemail;
	}

	// --- DATABASE MAPPING : PasswordQuestion (nvarchar)
	public void setPasswordquestion(String passwordquestion) {
		this.passwordquestion = passwordquestion;
	}

	public String getPasswordquestion() {
		return this.passwordquestion;
	}

	// --- DATABASE MAPPING : PasswordAnswer (nvarchar)
	public void setPasswordanswer(String passwordanswer) {
		this.passwordanswer = passwordanswer;
	}

	public String getPasswordanswer() {
		return this.passwordanswer;
	}

	// --- DATABASE MAPPING : IsApproved (bit)
	public void setIsapproved(Boolean isapproved) {
		this.isapproved = isapproved;
	}

	public Boolean getIsapproved() {
		return this.isapproved;
	}

	// --- DATABASE MAPPING : IsLockedOut (bit)
	public void setIslockedout(Boolean islockedout) {
		this.islockedout = islockedout;
	}

	public Boolean getIslockedout() {
		return this.islockedout;
	}

	// --- DATABASE MAPPING : CreateDate (datetime)
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	// --- DATABASE MAPPING : LastLoginDate (datetime)
	public void setLastlogindate(Date lastlogindate) {
		this.lastlogindate = lastlogindate;
	}

	public Date getLastlogindate() {
		return this.lastlogindate;
	}

	// --- DATABASE MAPPING : LastPasswordChangedDate (datetime)
	public void setLastpasswordchangeddate(Date lastpasswordchangeddate) {
		this.lastpasswordchangeddate = lastpasswordchangeddate;
	}

	public Date getLastpasswordchangeddate() {
		return this.lastpasswordchangeddate;
	}

	// --- DATABASE MAPPING : LastLockoutDate (datetime)
	public void setLastlockoutdate(Date lastlockoutdate) {
		this.lastlockoutdate = lastlockoutdate;
	}

	public Date getLastlockoutdate() {
		return this.lastlockoutdate;
	}

	// --- DATABASE MAPPING : FailedPasswordAttemptCount (int)
	public void setFailedpasswordattemptcount(Integer failedpasswordattemptcount) {
		this.failedpasswordattemptcount = failedpasswordattemptcount;
	}

	public Integer getFailedpasswordattemptcount() {
		return this.failedpasswordattemptcount;
	}

	// --- DATABASE MAPPING : FailedPasswordAttemptWindowStart (datetime)
	public void setFailedpasswordattemptwindowstart(Date failedpasswordattemptwindowstart) {
		this.failedpasswordattemptwindowstart = failedpasswordattemptwindowstart;
	}

	public Date getFailedpasswordattemptwindowstart() {
		return this.failedpasswordattemptwindowstart;
	}

	// --- DATABASE MAPPING : FailedPasswordAnswerAttemptCount (int)
	public void setFailedpasswordanswerattemptcount(Integer failedpasswordanswerattemptcount) {
		this.failedpasswordanswerattemptcount = failedpasswordanswerattemptcount;
	}

	public Integer getFailedpasswordanswerattemptcount() {
		return this.failedpasswordanswerattemptcount;
	}

	// --- DATABASE MAPPING : FailedPasswordAnswerAttemptWindowStart (datetime)
	public void setFailedpasswordanswerattemptwindowstart(Date failedpasswordanswerattemptwindowstart) {
		this.failedpasswordanswerattemptwindowstart = failedpasswordanswerattemptwindowstart;
	}

	public Date getFailedpasswordanswerattemptwindowstart() {
		return this.failedpasswordanswerattemptwindowstart;
	}

	// --- DATABASE MAPPING : Comment (ntext)
	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getComment() {
		return this.comment;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(userid);
		sb.append(applicationid);
		sb.append("|");
		sb.append(password);
		sb.append("|");
		sb.append(passwordformat);
		sb.append("|");
		sb.append(passwordsalt);
		sb.append("|");
		sb.append(mobilepin);
		sb.append("|");
		sb.append(email);
		sb.append("|");
		sb.append(loweredemail);
		sb.append("|");
		sb.append(passwordquestion);
		sb.append("|");
		sb.append(passwordanswer);
		sb.append("|");
		sb.append(isapproved);
		sb.append("|");
		sb.append(islockedout);
		sb.append("|");
		sb.append(createdate);
		sb.append("|");
		sb.append(lastlogindate);
		sb.append("|");
		sb.append(lastpasswordchangeddate);
		sb.append("|");
		sb.append(lastlockoutdate);
		sb.append("|");
		sb.append(failedpasswordattemptcount);
		sb.append("|");
		sb.append(failedpasswordattemptwindowstart);
		sb.append("|");
		sb.append(failedpasswordanswerattemptcount);
		sb.append("|");
		sb.append(failedpasswordanswerattemptwindowstart);
		sb.append("|");
		sb.append(comment);
		return sb.toString();
	}
}
