/*
 * 
 * Generated by prabhakar
*/
package com.gotracrat.managelocation.utils;

/**
 * Criteria bean used for Item search.
 * 
 * @author prabhakar
 */
public class ItemCriteria {

	private String tag;
	private int statusId;
	private int locationId;
	private int itemTypeId;

	public ItemCriteria(String tag, int statusId, int locationId, int itemTypeId) {
		super();
		this.tag = tag;
		this.statusId = statusId;
		this.locationId = locationId;
		this.itemTypeId = itemTypeId;
	}

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public int getStatusId() {
		return statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public int getLocationId() {
		return locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	public int getItemTypeId() {
		return itemTypeId;
	}

	public void setItemTypeId(int itemTypeId) {
		this.itemTypeId = itemTypeId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(tag);
		sb.append("|");
		sb.append(locationId);
		sb.append("|");
		sb.append(statusId);
		return sb.toString();
	}
}
