/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:22 )
 * Generated by 
*/
package com.gotracrat.managelocation.service;

import java.util.List;

import com.gotracrat.managelocation.resource.AspnetMembershipResource;
import com.gotracrat.managelocation.resource.LogManagementResource;
import com.gotracrat.managelocation.entity.AspnetMembership;
import com.gotracrat.managelocation.entity.UserLog;

/**
 * Service interface for AspnetMembership.
 * @author Prabhakar
 */
public interface AspnetMembershipService {

	
	/**
	 * Recover an aspnetMembership following an id.
	 * @param id the given id
	 * @return the aspnetMembership
	 */
	public AspnetMembership get(String userid);
	public List<LogManagementResource> getUserlog(String companyid);
	public List<UserLog> getUserlogDetails(Integer companyid,String userName);
	public Integer getUserCountByEmail(String emailid);

	/**
	 * Perform an aspnetMembership deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(String userid);

	/**
	 * Perform an aspnetMembership creation.
	 * @param aspnetMembership to create
	 * @return created aspnetMembership
	 */
	public AspnetMembership create(AspnetMembership aspnetMembership);

	/**
	 * Perform an aspnetMembership update.
	 * @param aspnetMembership to update
	 * @return state of update (true if ok otherwise false)
	 */
	public AspnetMembership save(AspnetMembership aspnetMembership);

	/**
	 * Test aspnetMembership existence.
	 * @param aspnetMembership to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(AspnetMembership aspnetMembership);

	public AspnetMembershipResource updateLoginDate(AspnetMembershipResource aspnetMembership);

	/**
	 * Perform an aspnetMembership update for User LoggedOutDate.
	 * @param userId to update
	 * @return state of update (true if ok otherwise false)
	 */
	public void updateUserLogOut(String userId);
	

}
