/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:21 )
 * Generated by Prabhakar
*/
package com.gotracrat.managelocation.service;

import java.util.Optional;

import com.gotracrat.managelocation.entity.AspnetApplications;

/**
 * Service interface for AspnetApplications.
 * @author Prabhakar
 */
public interface AspnetApplicationsService {

	
	/**
	 * Recover an aspnetApplications following an id.
	 * @param id the given id
	 * @return the aspnetApplications
	 */
	public Optional<AspnetApplications> get(String applicationid);

	/**
	 * Perform an aspnetApplications deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(String applicationid);

	/**
	 * Perform an aspnetApplications creation.
	 * @param aspnetApplications to create
	 * @return created aspnetApplications
	 */
	public AspnetApplications create(AspnetApplications aspnetApplications);

	/**
	 * Perform an aspnetApplications update.
	 * @param aspnetApplications to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Boolean save(AspnetApplications aspnetApplications);

	/**
	 * Test aspnetApplications existence.
	 * @param aspnetApplications to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(AspnetApplications aspnetApplications);
}
