/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:21 )
 * Generated by Prabhakar
*/
package com.gotracrat.managelocation.service;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.gotracrat.managelocation.entity.AspnetApplications;
import com.gotracrat.managelocation.repository.AspnetApplicationsRepository;

/**
 * Service implementation for AspnetApplications.
 * 
 * @author Prabhakar
 */
@Service
public class AspnetApplicationsServiceImpl implements AspnetApplicationsService {

	@Autowired
	private AspnetApplicationsRepository aspnetApplicationsRepository;

	@Override
	public Optional<AspnetApplications> get(String applicationid) {
		return aspnetApplicationsRepository.findById(applicationid);
	}

	@Override
	public Boolean delete(String applicationid) {
		if (aspnetApplicationsRepository.findById(applicationid).isPresent()) {
			aspnetApplicationsRepository.deleteById(applicationid);
			return true;
		}
		return false;
	}

	@Override
	public AspnetApplications create(AspnetApplications aspnetApplications) {
		return aspnetApplicationsRepository.save(aspnetApplications);
	}

	@Override
	public Boolean save(AspnetApplications aspnetApplications) {
		final String pk = aspnetApplications.getApplicationid();
		if (aspnetApplicationsRepository.findById(pk).isPresent()) {
			aspnetApplicationsRepository.save(aspnetApplications);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(AspnetApplications aspnetApplications) {
		return aspnetApplicationsRepository.existsById(aspnetApplications.getApplicationid());
	}

}
