/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:23 )
 * Generated by 
*/
package com.gotracrat.managelocation.service;

import com.gotracrat.managelocation.resource.ProfileResource;
import com.gotracrat.managelocation.entity.Profile;

/**
 * Service interface for Profile.
 * 
 * @author Prabhakar
 */
public interface ProfileService {

	/**
	 * Recover an profile following an id.
	 * 
	 * @param id the given id
	 * @return the profile
	 */
	public Profile get(Integer profileid);

	public ProfileResource getProfileWithUserId(String userid);

	/**
	 * Perform an profile deletion.
	 * 
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public Boolean delete(Integer profileid);

	/**
	 * Perform an profile creation.
	 * 
	 * @param profile to create
	 * @return created profile
	 */
	public Profile create(Profile profile);

	/**
	 * Perform an profile update.
	 * 
	 * @param profile to update
	 * @return state of update (true if ok otherwise false)
	 */
	public Profile save(Profile profile);

	/**
	 * Test profile existence.
	 * 
	 * @param profile to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Profile profile);

	ProfileResource save(ProfileResource profileResource, Integer profileId, Integer companyId);

	ProfileResource saveProfile(ProfileResource profileResource, Integer profileId, Integer companyId);

}
