/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:24 )
 * Generated by 
*/
package com.gotracrat.managelocation.service;

import com.gotracrat.managelocation.resource.ReportSecurityResource;
import com.gotracrat.managelocation.entity.Reportsecurity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Service interface for Reportsecurity.
 * @author Prabhakar
 */
public interface ReportSecurityService {

	/**
	 * Perform a pageable and filtered search.
	 * @param pageable pagination configuration
	 * @return a page of reportsecurity
	 */
	public Page<Reportsecurity> search(Pageable pageable);
	/**
	 * Recover an reportsecurity following an id.
	 * @param id the given id
	 * @return the reportsecurity
	 */
	public Reportsecurity get(Integer profileid);

	/**
	 * Perform an reportsecurity deletion.
	 * @param id the given id
	 * @return state of deletion (true if ok otherwise false)
	 */
	public String delete(Integer profileid);

	/**
	 * Perform an reportsecurity creation.
	 * @param reportsecurity to create
	 * @return created reportsecurity
	 */
	public Reportsecurity create(Reportsecurity reportsecurity);

	/**
	 * Perform an reportsecurity update.
	 * @param reportsecurity to update
	 * @return state of update (true if ok otherwise false)
	 */
	public ReportSecurityResource save(ReportSecurityResource reportsecurity);

	/**
	 * Test reportsecurity existence.
	 * @param reportsecurity to check
	 * @return true if author exist otherwise false
	 */
	public Boolean exist(Reportsecurity reportsecurity);
}
