/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:22 )
 * Generated by 
*/
package com.gotracrat.managecompany.repository;

import com.gotracrat.managecompany.entity.AspnetUsers;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for AspnetUsers.
 * 
 * @author Parasuram
 */
@Repository
public interface AspnetUsersRepository
		extends JpaRepository<AspnetUsers, String>, JpaSpecificationExecutor<AspnetUsers> {

	String fetchUserByUserName = "SELECT * FROM aspnet_Users u WHERE u.UserName = ?1";

	@Query(value = fetchUserByUserName, nativeQuery = true)
	AspnetUsers fetchUserByUserName(@Param("UserName") String userName);

}