/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:25 )
 * Generated by 
*/
package com.gotracrat.managecompany.repository;


import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.gotracrat.managecompany.entity.Usersecurity;
import com.gotracrat.managecompany.entity.UsersecurityKey;

/**
 * Jpa repository for Usersecurity.
 * @author Prabhakar
 */
@Repository
public interface UsersecurityRepository  extends JpaRepository<Usersecurity, UsersecurityKey>, JpaSpecificationExecutor<Usersecurity> {
public List<Usersecurity> findByCompositePrimaryKeyUserid(String userid);
}
//public List<Attributevalue> findByCompositePrimaryKeyEntityidAndCompositePrimaryKeyEntitytypeid(Integer locationId, int entityTypeId);

