/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:23 )
 * Generated by 
*/
package com.gotracrat.managelocation.resource;

import java.util.Date;

/**
 * Hateoas resource associated with AspnetUsers.
 * @author Prabhakar
 */
public class AspnetUsersResource  {

    private String applicationid;  
    private String userid;  
    private String username;  
    private String loweredusername;  
    private String mobilealias;  
    private Boolean isanonymous;  
    private Date lastactivitydate;  
    private String password;  
    private Integer passwordformat;  
    private String passwordsalt;  
    private String mobilepin;  
    private String email;  
    private String loweredemail;  
    private String passwordquestion;  
    private String passwordanswer;  
    private Boolean isapproved;  
    private Boolean islockedout;  
    private Date createdate;  
    private Date lastlogindate;  
    private Date lastpasswordchangeddate;  
    private Date lastlockoutdate;  
    private Integer failedpasswordattemptcount;  
    private Date failedpasswordattemptwindowstart;  
    private Integer failedpasswordanswerattemptcount;  
    private Date failedpasswordanswerattemptwindowstart;  
    private String comment;  
    private Integer profileid;  
    
    private String firstname;  
    private String lastname;  
    private String jobtitle;  
    private String department;  
    private String phone;  
    private String mobilephone;  
    private String fax;  
    private Boolean acceptedterms;  
    private Boolean isowneradmin;  
    private Integer companyid;  
    private Boolean sendreceiverfq;  
    private Integer toplocationid;  
    private Integer preferredlocationid;  
    private Boolean hidepricing;  
    private Integer actualCompanyId;
    private String addedBy;



	// Constructor
	public AspnetUsersResource() {
		// Needed empty constructor for serialization
	}

	public String getApplicationid() {
		return this.applicationid;
	}
	public void setApplicationid(String applicationid) {
		this.applicationid = applicationid;
	}
	public String getUserid() {
		return this.userid;
	}
	public void setUserid(String userid) {
		this.userid = userid;
	}
	public String getUsername() {
		return this.username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getLoweredusername() {
		return this.loweredusername;
	}
	public void setLoweredusername(String loweredusername) {
		this.loweredusername = loweredusername;
	}
	public String getMobilealias() {
		return this.mobilealias;
	}
	public void setMobilealias(String mobilealias) {
		this.mobilealias = mobilealias;
	}
	public Boolean getIsanonymous() {
		return this.isanonymous;
	}
	public void setIsanonymous(Boolean isanonymous) {
		this.isanonymous = isanonymous;
	}
	public Date getLastactivitydate() {
		return this.lastactivitydate;
	}
	public void setLastactivitydate(Date lastactivitydate) {
		this.lastactivitydate = lastactivitydate;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getPasswordformat() {
		return passwordformat;
	}

	public void setPasswordformat(Integer passwordformat) {
		this.passwordformat = passwordformat;
	}

	public String getPasswordsalt() {
		return passwordsalt;
	}

	public void setPasswordsalt(String passwordsalt) {
		this.passwordsalt = passwordsalt;
	}

	public String getMobilepin() {
		return mobilepin;
	}

	public void setMobilepin(String mobilepin) {
		this.mobilepin = mobilepin;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLoweredemail() {
		return loweredemail;
	}

	public void setLoweredemail(String loweredemail) {
		this.loweredemail = loweredemail;
	}

	public String getPasswordquestion() {
		return passwordquestion;
	}

	public void setPasswordquestion(String passwordquestion) {
		this.passwordquestion = passwordquestion;
	}

	public String getPasswordanswer() {
		return passwordanswer;
	}

	public void setPasswordanswer(String passwordanswer) {
		this.passwordanswer = passwordanswer;
	}

	public Boolean getIsapproved() {
		return isapproved;
	}

	public void setIsapproved(Boolean isapproved) {
		this.isapproved = isapproved;
	}

	public Boolean getIslockedout() {
		return islockedout;
	}

	public void setIslockedout(Boolean islockedout) {
		this.islockedout = islockedout;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getLastlogindate() {
		return lastlogindate;
	}

	public void setLastlogindate(Date lastlogindate) {
		this.lastlogindate = lastlogindate;
	}

	public Date getLastpasswordchangeddate() {
		return lastpasswordchangeddate;
	}

	public void setLastpasswordchangeddate(Date lastpasswordchangeddate) {
		this.lastpasswordchangeddate = lastpasswordchangeddate;
	}

	public Date getLastlockoutdate() {
		return lastlockoutdate;
	}

	public void setLastlockoutdate(Date lastlockoutdate) {
		this.lastlockoutdate = lastlockoutdate;
	}

	public Integer getFailedpasswordattemptcount() {
		return failedpasswordattemptcount;
	}

	public void setFailedpasswordattemptcount(Integer failedpasswordattemptcount) {
		this.failedpasswordattemptcount = failedpasswordattemptcount;
	}

	public Date getFailedpasswordattemptwindowstart() {
		return failedpasswordattemptwindowstart;
	}

	public void setFailedpasswordattemptwindowstart(Date failedpasswordattemptwindowstart) {
		this.failedpasswordattemptwindowstart = failedpasswordattemptwindowstart;
	}

	public Integer getFailedpasswordanswerattemptcount() {
		return failedpasswordanswerattemptcount;
	}

	public void setFailedpasswordanswerattemptcount(Integer failedpasswordanswerattemptcount) {
		this.failedpasswordanswerattemptcount = failedpasswordanswerattemptcount;
	}

	public Date getFailedpasswordanswerattemptwindowstart() {
		return failedpasswordanswerattemptwindowstart;
	}

	public void setFailedpasswordanswerattemptwindowstart(Date failedpasswordanswerattemptwindowstart) {
		this.failedpasswordanswerattemptwindowstart = failedpasswordanswerattemptwindowstart;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Integer getProfileid() {
		return profileid;
	}

	public void setProfileid(Integer profileid) {
		this.profileid = profileid;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getJobtitle() {
		return jobtitle;
	}

	public void setJobtitle(String jobtitle) {
		this.jobtitle = jobtitle;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobilephone() {
		return mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Boolean getAcceptedterms() {
		return acceptedterms;
	}

	public void setAcceptedterms(Boolean acceptedterms) {
		this.acceptedterms = acceptedterms;
	}

	public Boolean getIsowneradmin() {
		return isowneradmin;
	}

	public void setIsowneradmin(Boolean isowneradmin) {
		this.isowneradmin = isowneradmin;
	}

	public Integer getCompanyid() {
		return companyid;
	}

	public void setCompanyid(Integer companyid) {
		this.companyid = companyid;
	}

	public Boolean getSendreceiverfq() {
		return sendreceiverfq;
	}

	public void setSendreceiverfq(Boolean sendreceiverfq) {
		this.sendreceiverfq = sendreceiverfq;
	}

	public Integer getToplocationid() {
		return toplocationid;
	}

	public void setToplocationid(Integer toplocationid) {
		this.toplocationid = toplocationid;
	}

	public Integer getPreferredlocationid() {
		return preferredlocationid;
	}

	public void setPreferredlocationid(Integer preferredlocationid) {
		this.preferredlocationid = preferredlocationid;
	}

	public Boolean getHidepricing() {
		return hidepricing;
	}

	public void setHidepricing(Boolean hidepricing) {
		this.hidepricing = hidepricing;
	}

	public Integer getActualCompanyId() {
		return actualCompanyId;
	}

	public void setActualCompanyId(Integer actualCompanyId) {
		this.actualCompanyId = actualCompanyId;
	}

	public String getAddedBy() {
		return addedBy;
	}

	public void setAddedBy(String addedBy) {
		this.addedBy = addedBy;
	}
	
}
