/*
 * Created on 2018-11-29 ( Date ISO 2018-11-29 - Time 19:27:59 )
 * Generated by Prabhakar
*/
package com.gotracrat.managelocation.resource;

/**
 * Hateoas resource associated with Failuretype.
 * @author Prabhakar
 */
public class FailuretypeResource  {

    private Integer failuretypeid;  
    private Integer itemtypeid;  
    private String description;  
    private String lastmodifiedby;
    public String getLastmodifiedby() {
		return lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	private Integer companyId;
    private String causes;  

	// Constructor
	public FailuretypeResource() {
		// Needed empty constructor for serialization
	}

	public Integer getFailuretypeid() {
		return this.failuretypeid;
	}
	public void setFailuretypeid(Integer failuretypeid) {
		this.failuretypeid = failuretypeid;
	}
	public Integer getItemtypeid() {
		return this.itemtypeid;
	}
	public void setItemtypeid(Integer itemtypeid) {
		this.itemtypeid = itemtypeid;
	}
	public String getDescription() {
		return this.description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getCauses() {
		return this.causes;
	}
	public void setCauses(String causes) {
		this.causes = causes;
	}
}
