/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:23 )
 * Generated by
 */
package com.gotracrat.managelocation.resource;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;


/**
 * Hateoas resource associated with Profile.
 *
 * @author Prabhakar
 */
@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ProfileResource {

    private Integer profileid;
    private String userid;
    private String firstname;
    private String lastname;
    private String fullName;
    private String username;
    private String email;
    private String jobtitle;
    private String department;
    private String phone;
    private String mobilephone;
    private String fax;
    private Boolean acceptedterms;
    private Boolean isowneradmin;
    private Integer companyid;
    private Boolean sendreceiverfq;
    private Integer toplocationid;
    private Integer preferredlocationid;
    private Boolean hidepricing;
    private Integer userTypeId;
    private List<AttributeValueResource> attributevalues;
    private Integer actualCompanyId;
    private String addedBy;
    private Boolean isOwnerAdminReadOnly;
}
