/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:24 )
 * Generated by 
*/
package com.gotracrat.managelocation.resource;

/**
 * Hateoas resource associated with Reportsecurity.
 * @author Prabhakar
 */
public class ReportSecurityResource {

    private Integer profileid;  
    private Boolean inservicespare;  
    private Boolean warrantystatus;  
    private Boolean failureunderwarranty;  
    private Boolean mtbs;  
    private Boolean repaircostbyvendor;  
    private Boolean repaircostbylocation;  
    private Boolean equipmentinrepair;  
    private Boolean causeoffailure;  
    private Boolean costsavings;  
    private Boolean rawrepairdata;  
    private Boolean stocklevel;  
    private Boolean transferlog;  
    private Boolean repairstatus;  

	// Constructor
	public ReportSecurityResource() {
		// Needed empty constructor for serialization
	}

	public Integer getProfileid() {
		return this.profileid;
	}
	public void setProfileid(Integer profileid) {
		this.profileid = profileid;
	}
	public Boolean getInservicespare() {
		return this.inservicespare;
	}
	public void setInservicespare(Boolean inservicespare) {
		this.inservicespare = inservicespare;
	}
	public Boolean getWarrantystatus() {
		return this.warrantystatus;
	}
	public void setWarrantystatus(Boolean warrantystatus) {
		this.warrantystatus = warrantystatus;
	}
	public Boolean getFailureunderwarranty() {
		return this.failureunderwarranty;
	}
	public void setFailureunderwarranty(Boolean failureunderwarranty) {
		this.failureunderwarranty = failureunderwarranty;
	}
	public Boolean getMtbs() {
		return this.mtbs;
	}
	public void setMtbs(Boolean mtbs) {
		this.mtbs = mtbs;
	}
	public Boolean getRepaircostbyvendor() {
		return this.repaircostbyvendor;
	}
	public void setRepaircostbyvendor(Boolean repaircostbyvendor) {
		this.repaircostbyvendor = repaircostbyvendor;
	}
	public Boolean getRepaircostbylocation() {
		return this.repaircostbylocation;
	}
	public void setRepaircostbylocation(Boolean repaircostbylocation) {
		this.repaircostbylocation = repaircostbylocation;
	}
	public Boolean getEquipmentinrepair() {
		return this.equipmentinrepair;
	}
	public void setEquipmentinrepair(Boolean equipmentinrepair) {
		this.equipmentinrepair = equipmentinrepair;
	}
	public Boolean getCauseoffailure() {
		return this.causeoffailure;
	}
	public void setCauseoffailure(Boolean causeoffailure) {
		this.causeoffailure = causeoffailure;
	}
	public Boolean getCostsavings() {
		return this.costsavings;
	}
	public void setCostsavings(Boolean costsavings) {
		this.costsavings = costsavings;
	}
	public Boolean getRawrepairdata() {
		return this.rawrepairdata;
	}
	public void setRawrepairdata(Boolean rawrepairdata) {
		this.rawrepairdata = rawrepairdata;
	}
	public Boolean getStocklevel() {
		return this.stocklevel;
	}
	public void setStocklevel(Boolean stocklevel) {
		this.stocklevel = stocklevel;
	}
	public Boolean getTransferlog() {
		return this.transferlog;
	}
	public void setTransferlog(Boolean transferlog) {
		this.transferlog = transferlog;
	}
	public Boolean getRepairstatus() {
		return this.repairstatus;
	}
	public void setRepairstatus(Boolean repairstatus) {
		this.repairstatus = repairstatus;
	}
}
