/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:22 )
 * Generated by 
*/
package com.gotracrat.managelocation.repository;

import com.gotracrat.managelocation.entity.AspnetMembership;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for AspnetMembership.
 * @author Prabhakar
 */
@Repository
public interface AspnetMembershipRepository  extends JpaRepository<AspnetMembership, String>, JpaSpecificationExecutor<AspnetMembership> {
	
	
	
}