/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:23 )
 * Generated by 
*/
package com.gotracrat.managelocation.repository;

import com.gotracrat.managelocation.entity.Profile;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Profile.
 * @author Prabhakar
 */
@Repository
public interface ProfileRepository  extends JpaRepository<Profile, Integer>, JpaSpecificationExecutor<Profile> {



	public List<Profile> findAllBycompanyid(Integer companyid);
	
	public Profile findByprofileidAndCompanyid(Integer profileId,Integer companyId);

}