/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:24 )
 * Generated by 
*/
package com.gotracrat.managelocation.repository;

import com.gotracrat.managelocation.entity.Reportsecurity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Reportsecurity.
 * @author Prabhakar
 */
@Repository
public interface ReportsecurityRepository  extends JpaRepository<Reportsecurity, Integer>, JpaSpecificationExecutor<Reportsecurity> {}