/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:22 )
 * Generated by 
*/
package com.gotracrat.managelocation.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.gotracrat.managelocation.entity.AspnetUsers;

/**
 * Jpa repository for AspnetUsers.
 * @author Prabhakar
 */
@Repository
public interface UsersRepository  extends JpaRepository<AspnetUsers, String>, JpaSpecificationExecutor<AspnetUsers> {
    AspnetUsers findByUsername(String userName);
}