/*
 * Created on 2018-10-27 ( Date ISO 2018-10-27 - Time 19:57:25 )
 * Generated by 
*/
package com.gotracrat.managelocation.repository;

import com.gotracrat.managelocation.entity.UserSecurity;
import com.gotracrat.managelocation.entity.UsersecurityKey;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Usersecurity.
 * @author Prabhakar
 */
@Repository
public interface UserSecurityRepository extends JpaRepository<UserSecurity, UsersecurityKey>, JpaSpecificationExecutor<UserSecurity> {
public List<UserSecurity> findByCompositePrimaryKeyUserid(String userid);
}
//public List<Attributevalue> findByCompositePrimaryKeyEntityidAndCompositePrimaryKeyEntitytypeid(Integer locationId, int entityTypeId);

