/*
 * Created on 2018-08-13 ( Date ISO 2018-08-13 - Time 16:50:45 )
 * Generated by prabhakar
*/
package com.gotracrat.managelocation.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.gotracrat.managelocation.entity.WarrantyType;

/**
 * Jpa repository for Warrantytype.
 * 
 * @author prabhakar
 */
@Repository
public interface WarrantyTypeRepository
		extends JpaRepository<WarrantyType, Integer>, JpaSpecificationExecutor<WarrantyType> {

	public List<WarrantyType> findByCompanyCompanyid(int companyId);
}